server:
  port: 8099

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?serverTimezone=UTC&characterEncoding=UTF-8
    username: study
    password: root

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
    redis:
      host: localhost
      port: 6379
  session:
    jdbc:
      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

file:
  baseDir: /Users/ijichang/Desktop/upload

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.stat: DEBUG

jwt:
  header : Authorization
  expiration_time: 10 #1일
#  expiration_time: 86400000 #1일
  refresh_expiration_time: 20 #1일
  secret: 86b396ea240545aee0aa35daa40f03b9b2d51651382d4a3cdd02b0d304a93949

